import { Lato } from "next/font/google";
import "./globals.css";
import NavbarWrapper from "@/utils/navbar-wrapper";
import ReduxProvider from "@/utils/redux-provider";

const lato = Lato({
    variable: "--font-lato",
    subsets: ["latin"],
    weight: ["100", "300", "400", "700", "900"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={`${lato.variable} antialiased`}
            >
                <ReduxProvider>
                    <NavbarWrapper />
                    {children}
                </ReduxProvider>
            </body>
        </html>
    );
}
